### ISSUE TITLE
GPIO Page not displaying data in some columns

### ISSUE THREAD

**Issue by mjunek** [computergeek1507/CapeEEPROMViewer#1]
As per below screenshot - GPIO page - Type, command and args columns are not displaying information despite being defined in the EEPROM cape-inputs.json

![image](https://user-images.githubusercontent.com/55641392/194786529-8562bf55-a5ae-4626-9333-45987a3a3f40.png)

And how they appear within FPP
![image](https://user-images.githubusercontent.com/55641392/194786658-e1ea9528-ad22-4c21-a4b9-c88e49a34f12.png)

EEPROM file attached.

[HE123D-SN-de97de6c9064-v6.0.eeprom.zip](https://github.com/computergeek1507/CapeEEPROMViewer/files/9742878/HE123D-SN-de97de6c9064-v6.0.eeprom.zip)

**Comment by computergeek1507** [comment]
fixed in 42b721ac917bde67099a410d94f6ddf7828095db

https://github.com/computergeek1507/CapeEEPROMViewer/suites/8689977484/artifacts/391965047

**Comment by mjunek** [comment]
Looking good at my end - thanks for the fix

![image](https://user-images.githubusercontent.com/55641392/194795098-5b424de8-749f-45d0-9e95-0e3cdef15d02.png)
